import React, { useState, useEffect } from 'react';
import { FileText } from 'lucide-react';
import api from '../../services/api';

const artifactTexts = [
    { name: "Model Comparison Report", file: "model_comparison.txt" },
    { name: "Stratified K-Fold CV Results", file: "cross_validation_results.txt" },
    { name: "Random Forest Metrics", file: "rf_metrics.txt" }
];

export default function StaticArtifacts() {
    const [textContents, setTextContents] = useState({});

    useEffect(() => {
        const fetchTexts = async () => {
            const results = {};
            for (const item of artifactTexts) {
                try {
                    const res = await api.get(`/dev/results/${item.file}`);
                    results[item.file] = res.data.content;
                } catch (err) {
                    console.error("Error fetching", item.file, err);
                    results[item.file] = "Failed to load document. Check if the artifact was generated by the backend.";
                }
            }
            setTextContents(results);
        };
        fetchTexts();
    }, []);

    return (
        <div className="mt-12 w-full">
            <div className="text-center mb-8">
                <h2 className="text-3xl font-extrabold text-green-700 tracking-tight flex justify-center items-center gap-2">
                    <FileText size={32} /> Raw Evaluation Logs
                </h2>
                <p className="text-gray-500 font-medium mt-2">
                    Textual logs directly from the backend modeling engine detailing precision/recall and exact system outputs across runs.
                </p>
                <hr className="max-w-md mx-auto my-6 border-gray-200" />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 w-full items-start">
                {artifactTexts.map((txt, idx) => (
                    <div key={idx} className="bg-white rounded-2xl p-5 shadow-sm border border-gray-200 flex flex-col hover:shadow-md transition-shadow">
                        <h4 className="font-bold text-gray-700 mb-1 leading-tight flex items-center gap-2">
                            <span className="p-1.5 bg-gray-100 rounded-lg text-gray-500"><FileText size={16} /></span>
                            {txt.name}
                        </h4>
                        <p className="text-xs text-gray-400 font-mono mb-4">{txt.file}</p>

                        <div className="bg-gray-900 rounded-xl p-4 overflow-x-auto shadow-inner h-[300px] overflow-y-auto">
                            <pre className="text-gray-300 font-mono text-xs leading-relaxed">
                                {textContents[txt.file] || "Loading logs from server..."}
                            </pre>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
